Repository one-step-team/one-step-app, pull requests merged in 2024-01, with the labels that each got.

#51 Home Button
  core/data/src/main/java/com/colddelight/data/di/DataModule.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/util/Common.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/dao/RoutineDayDao.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/EditText.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/Navigation.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/SetButton.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/icons/__IconPack.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/icons/iconpack/Day.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/icons/iconpack/Delete.kt
  core/model/src/main/java/com/colddelight/model/ExerciseDay.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/navigation/ExerciseDetailNavigation.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeUiState.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
  feature/home/src/main/java/com/colddelight/home/UserState.kt
Labels: Feature

#52 [Feature] ExerciseDetailItem
  core/designsystem/src/main/java/com/colddelight/designsystem/component/ExerciseDetailItem.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
Labels: Feature

#54 [Setting] DB수정
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/StepDatabase.kt
  core/database/src/main/java/com/colddelight/database/dao/BodyWeightDao.kt
  core/database/src/main/java/com/colddelight/database/dao/ExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/dao/FreeExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/di/LocalDataModule.kt
  core/database/src/main/java/com/colddelight/database/model/BodyWeightEntity.kt
  core/database/src/main/java/com/colddelight/database/model/DayExerciseEntity.kt
  core/database/src/main/java/com/colddelight/database/model/FreeExerciseEntity.kt
  core/database/src/main/java/com/colddelight/database/model/HistoryEntity.kt
  core/database/src/main/java/com/colddelight/database/model/HistoryExerciseEntity.kt
  core/database/src/main/java/com/colddelight/database/model/RoutineDayEntity.kt
  core/database/src/main/java/com/colddelight/database/model/RoutineEntity.kt
  core/model/src/main/java/com/colddelight/model/Exercise.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
  feature/home/src/main/java/com/colddelight/home/navigation/HomeNavigation.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Setting

#55 [Feature] 타이머
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/RoutineDayDao.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailViewModel.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
Labels: Feature

#56 Feature/routine
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/DayExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/dao/RoutineDayDao.kt
  core/model/src/main/java/com/colddelight/model/DayExercise.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Feature

#57 [Feature] Routine Screen Detail 수정중
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Feature

#58 [Feature] 세트 추가, 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/colddelight/onestep/navigation/StepNavHost.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryExerciseDao.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseDetailUiState.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseUiState.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercise/src/main/java/com/colddelight/exercise/navigation/ExerciseNavigation.kt
  feature/exercisedetail/src/main/AndroidManifest.xml
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/navigation/ExerciseDetailNavigation.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
Labels: Feature

#59 [Feature] History 캘린더 작업중
  app/build.gradle.kts
  core/data/src/main/java/com/colddelight/data/di/DataModule.kt
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/theme/Type.kt
  feature/history/build.gradle.kts
  feature/history/src/main/java/com/colddelight/history/HistoryScreen.kt
  feature/history/src/main/java/com/colddelight/history/HistoryViewModel.kt
Labels: Feature

#60 [Feature] DayExercise Item이 제대로 변경되지 않던 문제 해결, 자잘한 화면 디테일 변경
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Feature

#61 [Feature] History Page 필요한 정보 불러오는 것 완성
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryExerciseDao.kt
  core/model/src/main/java/com/colddelight/model/DayHistory.kt
  feature/history/src/main/java/com/colddelight/history/HistoryScreen.kt
  feature/history/src/main/java/com/colddelight/history/HistoryViewModel.kt
Labels: Feature

#62 [Feature] edit text
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/EditText.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/ExerciseDetailItem.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
Labels: Feature

#63 [Feature] HistoryExercise 로직
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/HomeRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/DayExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/model/HistoryExerciseEntity.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineViewModel.kt
Labels: Feature

#64 [Feature] Routine 이름 변경 완료, 오늘 요일 페이지 바로 보이도록 수정
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineViewModel.kt
Labels: Feature

#65 [Feature] History 디자인 적용
  core/designsystem/src/main/java/com/colddelight/designsystem/theme/Type.kt
  feature/history/src/main/java/com/colddelight/history/HistoryScreen.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Feature

#66 [Feature] kg,reps로직
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepository.kt
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/DayExerciseDao.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/dao/RoutineDayDao.kt
  core/database/src/main/java/com/colddelight/database/model/DayExerciseEntity.kt
  core/database/src/main/java/com/colddelight/database/model/RoutineDayEntity.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
Labels: Feature

#67 [Feature] 수정요구사항 일부 적용
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
  gradle/libs.versions.toml
Labels: Feature

#68 [Chore] 병합
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/colddelight/onestep/MainActivity.kt
  app/src/main/java/com/colddelight/onestep/navigation/TopLevelDestination.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/one_step_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  core/data/src/main/java/com/colddelight/data/repository/ExerciseRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/HistoryRepositoryImpl.kt
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  core/database/src/main/java/com/colddelight/database/dao/HistoryDao.kt
  core/database/src/main/java/com/colddelight/database/dao/RoutineDayDao.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/EditText.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/ExerciseDetailItem.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/ExerciseProgress.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/SetButton.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/theme/Theme.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseViewModel.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeScreen.kt
  feature/home/src/main/java/com/colddelight/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineViewModel.kt
Labels: Chore

#69 [Feature] RoutinePage 수정 요구사항 적용
  core/data/src/main/java/com/colddelight/data/repository/RoutineRepositoryImpl.kt
  feature/routine/src/main/java/com/colddelight/routine/RoutineScreen.kt
Labels: Feature

#70 [Feature] status bar text color
  app/src/main/java/com/colddelight/onestep/MainActivity.kt
  app/src/main/java/com/colddelight/onestep/ui/StepAppState.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/component/ExerciseProgress.kt
  core/designsystem/src/main/java/com/colddelight/designsystem/theme/Theme.kt
  feature/exercise/src/main/java/com/colddelight/exercise/ExerciseScreen.kt
  feature/exercisedetail/src/main/java/com/colddelight/exercisedetail/ExerciseDetailScreen.kt
Labels: Feature

#71 [Feature] History 달력의 요일을 한글 리스트로 변경
  feature/history/src/main/java/com/colddelight/history/HistoryScreen.kt
Labels: Feature

#75 인터넷 권한 제거
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/colddelight/onestep/ui/StepApp.kt
  app/src/main/res/drawable/one_step_splash.xml
  core/designsystem/src/main/java/com/colddelight/designsystem/component/TopAppBar.kt
Labels: Setting

#77 오픈소스 라이센스 목록 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/colddelight/onestep/MainActivity.kt
  app/src/main/java/com/colddelight/onestep/ui/StepApp.kt
  app/src/main/res/values/oss.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  core/designsystem/src/main/java/com/colddelight/designsystem/component/TopAppBar.kt
Labels: Setting
